In [76]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix

In [77]:
userbase1_dataframe = pd.read_csv("Dataset/ml-100k/u1.base", names=['user_id', 'item_id', 'rating', 'timestamp'], delimiter="\t")
userbase1_dataframe = userbase1_dataframe.drop(["timestamp"], axis=1)
userbase1_dataframe

       user_id  item_id  rating
0            1        1       5
1            1        2       3
2            1        3       4
3            1        4       3
4            1        5       3
...        ...      ...     ...
79995      943     1067       2
79996      943     1074       4
79997      943     1188       3
79998      943     1228       3
79999      943     1330       3

[80000 rows x 3 columns]

In [78]:
user_list = userbase1_dataframe['user_id'].unique().tolist()
user_list

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943]

In [79]:
usertest1_dataframe = pd.read_csv("Dataset/ml-100k/u1.test", names=['user_id', 'item_id', 'rating', 'timestamp'], delimiter="\t")
usertest1_dataframe = usertest1_dataframe.drop(["timestamp"], axis=1)
usertest1_dataframe

       user_id  item_id  rating
0            1        6       5
1            1       10       3
2            1       12       5
3            1       14       5
4            1       17       3
...        ...      ...     ...
19995      458      648       4
19996      458     1101       4
19997      459      934       3
19998      460       10       3
19999      462      682       5

[20000 rows x 3 columns]

In [80]:
# Convert DataFrame to sparse matrix
user_item_matrix = userbase1_dataframe.pivot(index='user_id', columns='item_id', values='rating').fillna(0)
user_item_matrix_sparse = csr_matrix(user_item_matrix.values)

# Calculate cosine similarity matrix
cosine_sim_matrix = cosine_similarity(user_item_matrix_sparse)
cosine_sim_matrix

array([[1.        , 0.09702087, 0.05246924, ..., 0.15815144, 0.13309031,
        0.25277792],
       [0.09702087, 1.        , 0.05134808, ..., 0.13280638, 0.1265973 ,
        0.10178363],
       [0.05246924, 0.05134808, 1.        , ..., 0.08353707, 0.08122974,
        0.01967584],
       ...,
       [0.15815144, 0.13280638, 0.08353707, ..., 1.        , 0.1016418 ,
        0.09511958],
       [0.13309031, 0.1265973 , 0.08122974, ..., 0.1016418 , 1.        ,
        0.18246466],
       [0.25277792, 0.10178363, 0.01967584, ..., 0.09511958, 0.18246466,
        1.        ]])

In [81]:
utility_matrix = userbase1_dataframe.pivot(index='user_id', columns='item_id', values='rating').fillna(0)
utility_matrix

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,0.0,4.0,1.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [82]:
# Convert cosine similarity matrix to DataFrame for better visualization
# Where both the rows and columns are labeled with user ids, and the values represent the cosine similarity between corresponding users based on their ratings.
cosine_sim_df = pd.DataFrame(cosine_sim_matrix, index=user_item_matrix.index, columns=user_item_matrix.index)
cosine_sim_df

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.097021,0.052469,0.021162,0.193545,0.290114,0.200438,0.097786,0.060791,0.200926,...,0.252187,0.090728,0.216186,0.139478,0.156937,0.095265,0.222958,0.158151,0.133090,0.252778
2,0.097021,1.000000,0.051348,0.084426,0.015516,0.187717,0.074479,0.023262,0.108167,0.078176,...,0.083045,0.298811,0.308608,0.403810,0.282896,0.213233,0.189257,0.132806,0.126597,0.101784
3,0.052469,0.051348,1.000000,0.145660,0.037180,0.084526,0.015718,0.086400,0.000000,0.030909,...,0.041330,0.036956,0.135750,0.063940,0.102082,0.034064,0.133720,0.083537,0.081230,0.019676
4,0.021162,0.084426,0.145660,1.000000,0.017291,0.000000,0.037566,0.046087,0.000000,0.023232,...,0.014238,0.047742,0.127305,0.118947,0.089016,0.039116,0.120521,0.135669,0.125925,0.035586
5,0.193545,0.015516,0.037180,0.017291,1.000000,0.158552,0.170890,0.157488,0.053846,0.089508,...,0.284295,0.074215,0.086345,0.063759,0.126358,0.068145,0.198118,0.142141,0.150000,0.239803
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.095265,0.213233,0.034064,0.039116,0.068145,0.099518,0.075901,0.039294,0.000000,0.031693,...,0.066039,0.431154,0.258021,0.226449,0.432666,1.000000,0.087687,0.180029,0.043264,0.144250
940,0.222958,0.189257,0.133720,0.120521,0.198118,0.289962,0.263561,0.094273,0.093677,0.246078,...,0.327153,0.107024,0.187536,0.181317,0.175158,0.087687,1.000000,0.145152,0.261376,0.241028
941,0.158151,0.132806,0.083537,0.135669,0.142141,0.093607,0.017469,0.106551,0.110612,0.014989,...,0.046952,0.203301,0.288318,0.234211,0.313400,0.180029,0.145152,1.000000,0.101642,0.095120
942,0.133090,0.126597,0.081230,0.125925,0.150000,0.178815,0.169986,0.067465,0.064484,0.156821,...,0.226440,0.073513,0.089588,0.129554,0.099385,0.043264,0.261376,0.101642,1.000000,0.182465
943,0.252778,0.101784,0.019676,0.035586,0.239803,0.210308,0.292691,0.214486,0.104008,0.130262,...,0.263791,0.210763,0.143253,0.077793,0.202244,0.144250,0.241028,0.095120,0.182465,1.000000

In [83]:
def rating_prediction_weighted(user_ids, cosine_sim_df, utility_matrix, top_n=10):
    all_predicted_ratings = []

    for user_id in user_ids:
        print(f"{user_id}/{len(user_ids)}")
        # Get cosine similarity scores for the given user
        user_similarity_scores = cosine_sim_df[user_id]

        # Sort users by similarity scores and get top N similar users (excluding the user itself)
        similar_users = user_similarity_scores.sort_values(ascending=False)[1:top_n+1]

        # Initialize a dictionary to store aggregated ratings from similar users
        predicted_ratings = {}

        # Aggregate ratings from similar users for items not yet rated by the given user
        unrated_items = utility_matrix.loc[user_id][utility_matrix.loc[user_id] == 0].index

        # Pre-calculate similarity scores for similar users
        similar_user_ids = similar_users.index
        similar_user_similarities = similar_users.values

        for item_id in unrated_items:
            # Get ratings of unrated items by similar users
            similar_user_ratings = utility_matrix.loc[similar_user_ids, item_id]

            # Calculate weighted sum and sum of weights
            weighted_sum = np.dot(similar_user_ratings, similar_user_similarities)
            sum_of_weights = np.sum(similar_user_similarities)

            # Calculate predicted rating if sum_of_weights is not zero
            if sum_of_weights != 0:
                predicted_rating = weighted_sum / sum_of_weights
                predicted_ratings[item_id] = predicted_rating

        # Append predicted ratings for the current user to the list
        all_predicted_ratings.extend([{'user_id': user_id, 'item_id': item_id, 'rating': rating} for item_id, rating in predicted_ratings.items()])

    return all_predicted_ratings

In [84]:
users_id = user_list
predict_items_df = rating_prediction_weighted(users_id, cosine_sim_df, utility_matrix, 50)

1/943
2/943
3/943
4/943
5/943
6/943
7/943
8/943
9/943
10/943
11/943
12/943
13/943
14/943
15/943
16/943
17/943
18/943
19/943
20/943
21/943
22/943
23/943
24/943
25/943
26/943
27/943
28/943
29/943
30/943
31/943
32/943
33/943
34/943
35/943
36/943
37/943
38/943
39/943
40/943
41/943
42/943
43/943
44/943
45/943
46/943
47/943
48/943
49/943
50/943
51/943
52/943
53/943
54/943
55/943
56/943
57/943
58/943
59/943
60/943
61/943
62/943
63/943
64/943
65/943
66/943
67/943
68/943
69/943
70/943
71/943
72/943
73/943
74/943
75/943
76/943
77/943
78/943
79/943
80/943
81/943
82/943
83/943
84/943
85/943
86/943
87/943
88/943
89/943
90/943
91/943
92/943
93/943
94/943
95/943
96/943
97/943
98/943
99/943
100/943
101/943
102/943
103/943
104/943
105/943
106/943
107/943
108/943
109/943
110/943
111/943
112/943
113/943
114/943
115/943
116/943
117/943
118/943
119/943
120/943
121/943
122/943
123/943
124/943
125/943
126/943
127/943
128/943
129/943
130/943
131/943
132/943
133/943
134/943
135/943
136/943
137/943
138/943
139/943
140/943
141/943
142/943
143/943
144/943
145/943
146/943
147/943
148/943
149/943
150/943
151/943
152/943
153/943
154/943
155/943
156/943
157/943
158/943
159/943
160/943
161/943
162/943
163/943
164/943
165/943
166/943
167/943
168/943
169/943
170/943
171/943
172/943
173/943
174/943
175/943
176/943
177/943
178/943
179/943
180/943
181/943
182/943
183/943
184/943
185/943
186/943
187/943
188/943
189/943
190/943
191/943
192/943
193/943
194/943
195/943
196/943
197/943
198/943
199/943
200/943
201/943
202/943
203/943
204/943
205/943
206/943
207/943
208/943
209/943
210/943
211/943
212/943
213/943
214/943
215/943
216/943
217/943
218/943
219/943
220/943
221/943
222/943
223/943
224/943
225/943
226/943
227/943
228/943
229/943
230/943
231/943
232/943
233/943
234/943
235/943
236/943
237/943
238/943
239/943
240/943
241/943
242/943
243/943
244/943
245/943
246/943
247/943
248/943
249/943
250/943
251/943
252/943
253/943
254/943
255/943
256/943
257/943
258/943
259/943
260/943
261/943
262/943
263/943
264/943
265/943
266/943
267/943
268/943
269/943
270/943
271/943
272/943
273/943
274/943
275/943
276/943
277/943
278/943
279/943
280/943
281/943
282/943
283/943
284/943
285/943
286/943
287/943
288/943
289/943
290/943
291/943
292/943
293/943
294/943
295/943
296/943
297/943
298/943
299/943
300/943
301/943
302/943
303/943
304/943
305/943
306/943
307/943
308/943
309/943
310/943
311/943
312/943
313/943
314/943
315/943
316/943
317/943
318/943
319/943
320/943
321/943
322/943
323/943
324/943
325/943
326/943
327/943
328/943
329/943
330/943
331/943
332/943
333/943
334/943
335/943
336/943
337/943
338/943
339/943
340/943
341/943
342/943
343/943
344/943
345/943
346/943
347/943
348/943
349/943
350/943
351/943
352/943
353/943
354/943
355/943
356/943
357/943
358/943
359/943
360/943
361/943
362/943
363/943
364/943
365/943
366/943
367/943
368/943
369/943
370/943
371/943
372/943
373/943
374/943
375/943
376/943
377/943
378/943
379/943
380/943
381/943
382/943
383/943
384/943
385/943
386/943
387/943
388/943
389/943
390/943
391/943
392/943
393/943
394/943
395/943
396/943
397/943
398/943
399/943
400/943
401/943
402/943
403/943
404/943
405/943
406/943
407/943
408/943
409/943
410/943
411/943
412/943
413/943
414/943
415/943
416/943
417/943
418/943
419/943
420/943
421/943
422/943
423/943
424/943
425/943
426/943
427/943
428/943
429/943
430/943
431/943
432/943
433/943
434/943
435/943
436/943
437/943
438/943
439/943
440/943
441/943
442/943
443/943
444/943
445/943
446/943
447/943
448/943
449/943
450/943
451/943
452/943
453/943
454/943
455/943
456/943
457/943
458/943
459/943
460/943
461/943
462/943
463/943
464/943
465/943
466/943
467/943
468/943
469/943
470/943
471/943
472/943
473/943
474/943
475/943
476/943
477/943
478/943
479/943
480/943
481/943
482/943
483/943
484/943
485/943
486/943
487/943
488/943
489/943
490/943
491/943
492/943
493/943
494/943
495/943
496/943
497/943
498/943
499/943
500/943
501/943
502/943
503/943
504/943
505/943
506/943
507/943
508/943
509/943
510/943
511/943
512/943
513/943
514/943
515/943
516/943
517/943
518/943
519/943
520/943
521/943
522/943
523/943
524/943
525/943
526/943
527/943
528/943
529/943
530/943
531/943
532/943
533/943
534/943
535/943
536/943
537/943
538/943
539/943
540/943
541/943
542/943
543/943
544/943
545/943
546/943
547/943
548/943
549/943
550/943
551/943
552/943
553/943
554/943
555/943
556/943
557/943
558/943
559/943
560/943
561/943
562/943
563/943
564/943
565/943
566/943
567/943
568/943
569/943
570/943
571/943
572/943
573/943
574/943
575/943
576/943
577/943
578/943
579/943
580/943
581/943
582/943
583/943
584/943
585/943
586/943
587/943
588/943
589/943
590/943
591/943
592/943
593/943
594/943
595/943
596/943
597/943
598/943
599/943
600/943
601/943
602/943
603/943
604/943
605/943
606/943
607/943
608/943
609/943
610/943
611/943
612/943
613/943
614/943
615/943
616/943
617/943
618/943
619/943
620/943
621/943
622/943
623/943
624/943
625/943
626/943
627/943
628/943
629/943
630/943
631/943
632/943
633/943
634/943
635/943
636/943
637/943
638/943
639/943
640/943
641/943
642/943
643/943
644/943
645/943
646/943
647/943
648/943
649/943
650/943
651/943
652/943
653/943
654/943
655/943
656/943
657/943
658/943
659/943
660/943
661/943
662/943
663/943
664/943
665/943
666/943
667/943
668/943
669/943
670/943
671/943
672/943
673/943
674/943
675/943
676/943
677/943
678/943
679/943
680/943
681/943
682/943
683/943
684/943
685/943
686/943
687/943
688/943
689/943
690/943
691/943
692/943
693/943
694/943
695/943
696/943
697/943
698/943
699/943
700/943
701/943
702/943
703/943
704/943
705/943
706/943
707/943
708/943
709/943
710/943
711/943
712/943
713/943
714/943
715/943
716/943
717/943
718/943
719/943
720/943
721/943
722/943
723/943
724/943
725/943
726/943
727/943
728/943
729/943
730/943
731/943
732/943
733/943
734/943
735/943
736/943
737/943
738/943
739/943
740/943
741/943
742/943
743/943
744/943
745/943
746/943
747/943
748/943
749/943
750/943
751/943
752/943
753/943
754/943
755/943
756/943
757/943
758/943
759/943
760/943
761/943
762/943
763/943
764/943
765/943
766/943
767/943
768/943
769/943
770/943
771/943
772/943
773/943
774/943
775/943
776/943
777/943
778/943
779/943
780/943
781/943
782/943
783/943
784/943
785/943
786/943
787/943
788/943
789/943
790/943
791/943
792/943
793/943
794/943
795/943
796/943
797/943
798/943
799/943
800/943
801/943
802/943
803/943
804/943
805/943
806/943
807/943
808/943
809/943
810/943
811/943
812/943
813/943
814/943
815/943
816/943
817/943
818/943
819/943
820/943
821/943
822/943
823/943
824/943
825/943
826/943
827/943
828/943
829/943
830/943
831/943
832/943
833/943
834/943
835/943
836/943
837/943
838/943
839/943
840/943
841/943
842/943
843/943
844/943
845/943
846/943
847/943
848/943
849/943
850/943
851/943
852/943
853/943
854/943
855/943
856/943
857/943
858/943
859/943
860/943
861/943
862/943
863/943
864/943
865/943
866/943
867/943
868/943
869/943
870/943
871/943
872/943
873/943
874/943
875/943
876/943
877/943
878/943
879/943
880/943
881/943
882/943
883/943
884/943
885/943
886/943
887/943
888/943
889/943
890/943
891/943
892/943
893/943
894/943
895/943
896/943
897/943
898/943
899/943
900/943
901/943
902/943
903/943
904/943
905/943
906/943
907/943
908/943
909/943
910/943
911/943
912/943
913/943
914/943
915/943
916/943
917/943
918/943
919/943
920/943
921/943
922/943
923/943
924/943
925/943
926/943
927/943
928/943
929/943
930/943
931/943
932/943
933/943
934/943
935/943
936/943
937/943
938/943
939/943
940/943
941/943
942/943
943/943

In [85]:
test_df = usertest1_dataframe
test_df

       user_id  item_id  rating
0            1        6       5
1            1       10       3
2            1       12       5
3            1       14       5
4            1       17       3
...        ...      ...     ...
19995      458      648       4
19996      458     1101       4
19997      459      934       3
19998      460       10       3
19999      462      682       5

[20000 rows x 3 columns]

In [86]:
# Convert dictionary to DataFrame
predict_items_df = pd.DataFrame(predict_items_df, columns=['user_id', 'item_id', 'rating'])
predict_items_df = predict_items_df.rename(columns={'rating': 'predicted_rating'})
predict_items_df

         user_id  item_id  predicted_rating
0              1        6          0.244093
1              1       10          0.668448
2              1       12          3.439058
3              1       14          1.157641
4              1       17          0.951065
...          ...      ...               ...
1475945      943     1678          0.000000
1475946      943     1679          0.000000
1475947      943     1680          0.000000
1475948      943     1681          0.063368
1475949      943     1682          0.059476

[1475950 rows x 3 columns]

In [87]:
def evaluate_mse(predicted_ratings_df, test_df):
    # Merge predicted ratings with test DataFrame on user_id and item_id
    merged_df = pd.merge(test_df, predicted_ratings_df, on=['item_id'], how='inner')

    # Compute squared error between predicted and actual ratings
    merged_df['squared_error'] = (merged_df['rating'] - merged_df['predicted_rating']) ** 2

    # Calculate mean squared error (MSE)
    mse = merged_df['squared_error'].mean()

    return mse

# Example usage
mse = evaluate_mse(predict_items_df, test_df)
print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 10.130175434643405

In [88]:
# Evaluation function
def evaluate_rmse(test_df, predicted_df):
    # Merge test and predicted DataFrames on item_id
    merged_df = test_df.merge(predicted_df, on='item_id', how='inner')

    # Compute Root Mean Squared Error (RMSE)
    rmse = np.sqrt(((merged_df['rating'] - merged_df['predicted_rating']) ** 2).mean())

    return rmse

rmse = evaluate_rmse(test_df, predict_items_df)
print("RMSE:", rmse)

RMSE: 3.1827936525391345