In [10]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
# Reading the dataset
userbase1_dataframe = pd.read_csv("dataset/ml-100k/u1.base", names=['user id', 'item id', 'rating', 'timestamp'], delimiter="\t")

In [12]:
# Let's assume you have another dataset containing movie information like movie_id, title, genres
movies_dataframe = pd.read_csv("dataset/ml-100k/u.item", delimiter="|", encoding="latin1",
                               names=["item id", "title", "release date", 
                                      "video release date", "IMDb URL", "unknown", 
                                      "Action", "Adventure", "Animation",
                                      "Children's", "Comedy", "Crime",
                                      "Documentary", "Drama", "Fantasy",
                                      "Film-Noir", "Horror", "Musical",
                                      "Mystery", "Romance", "Sci-Fi",
                                      "Thriller", "War", "Western"
                                      ])
movies_dataframe = movies_dataframe.drop(["unknown"], axis=1)

In [13]:
# Feature Extraction: Using movie genres for simplicity
# Created a string containing all genres for each movie
genres_columns = ["Action", "Adventure", "Animation", "Children's", 
                  "Comedy", "Crime", "Documentary", "Drama", "Fantasy",
                  "Film-Noir", "Horror", "Musical", "Mystery", "Romance",
                  "Sci-Fi", "Thriller", "War", "Western"]

In [14]:
def extract_genres(row):
    genres = [col for col in genres_columns if row[col] == 1]
    return ' '.join(genres)

In [15]:
movies_dataframe['genres'] = movies_dataframe.apply(extract_genres, axis=1)

In [16]:
# Vectorization
vectorizer = CountVectorizer(binary=True, lowercase=False)
genre_matrix = vectorizer.fit_transform(movies_dataframe['genres'])

In [17]:
def get_recommendations_genre(genres):
    # Convert the list of genres into a single string
    genres_string = ' '.join(genres)
    
    # Vectorize the provided genres
    genres_vector = vectorizer.transform([genres_string])
    
    # Calculate similarity with all movies
    genre_similarity = cosine_similarity(genres_vector, genre_matrix).flatten()
    
    # Get indices of top similar movies
    top_indices = genre_similarity.argsort()[::-1][1:51]  # Exclude the first, as it's the input itself
    
    # Get the movie titles and similarity scores
    recommended_movies = movies_dataframe.iloc[top_indices][['title']].copy()
    recommended_movies['similarity_score'] = genre_similarity[top_indices]
    
    return recommended_movies.reset_index()

In [18]:
# Example usage with a genre
genre_input = ["Action", "Thriller", "Adventure"]
recommended_movies_df = get_recommendations_genre(genre_input)
print(f"Recommended movies for the genre '{genre_input}':")
recommended_movies_df

Recommended movies for the genre '['Action', 'Thriller', 'Adventure']':

    index                                      title  similarity_score
0     117                             Twister (1996)          1.000000
1     929                      Chain Reaction (1996)          1.000000
2    1313                  Surviving the Game (1994)          1.000000
3    1015                             Con Air (1997)          1.000000
4    1012                            Anaconda (1997)          1.000000
5     826                            Daylight (1996)          1.000000
6     116                           Rock, The (1996)          1.000000
7     981                        Maximum Risk (1996)          1.000000
8     565            Clear and Present Danger (1994)          1.000000
9       1                           GoldenEye (1995)          1.000000
10    801                         Hard Target (1993)          0.866025
11    549          Die Hard: With a Vengeance (1995)          0.816497
12    545                        Broken Arrow (1996)          0.816497
13    540                       Mortal Kombat (1995)          0.816497
14     52                Natural Born Killers (1994)          0.816497
15    553                          Waterworld (1995)          0.816497
16   1018  Die xue shuang xiong (Killer, The) (1989)          0.816497
17   1033                          Quest, The (1996)          0.816497
18    490       Adventures of Robin Hood, The (1938)          0.816497
19   1594                            Shopping (1994)          0.816497
20    571                          Blown Away (1994)          0.816497
21    143                            Die Hard (1988)          0.816497
22     78                       Fugitive, The (1993)          0.816497
23    322                        Dante's Peak (1997)          0.816497
24    430                          Highlander (1986)          0.816497
25    348                           Hard Rain (1998)          0.816497
26    146            Long Kiss Goodnight, The (1996)          0.816497
27    147         Ghost and the Darkness, The (1996)          0.816497
28    173             Raiders of the Lost Ark (1981)          0.816497
29    209  Indiana Jones and the Last Crusade (1989)          0.816497
30    127                            Supercop (1992)          0.816497
31   1522               Good Man in Africa, A (1994)          0.816497
32    225                          Die Hard 2 (1990)          0.816497
33   1392                                Stag (1997)          0.816497
34    264           Hunt for Red October, The (1990)          0.816497
35    265                  Kull the Conqueror (1997)          0.816497
36    280                     River Wild, The (1994)          0.816497
37   1547                       The Courtyard (1995)          0.816497
38    294                           Breakdown (1997)          0.816497
39    299                       Air Force One (1997)          0.816497
40    330                           Edge, The (1997)          0.816497
41    596                              Eraser (1996)          0.816497
42    840                    Glimmer Man, The (1996)          0.816497
43    751            Replacement Killers, The (1998)          0.816497
44    742           Crow: City of Angels, The (1996)          0.816497
45    678                 Conan the Barbarian (1981)          0.816497
46   1672                              Mirage (1995)          0.816497
47    889         Mortal Kombat: Annihilation (1997)          0.816497
48    679                  Kull the Conqueror (1997)          0.816497
49    683                 In the Line of Fire (1993)          0.816497